config/routes.rb
Rails.application.routes.draw do

  resources :admins
  get 'sessions/new'

  resources :reports
  resources :people
  resources :police

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  post '/mlogin', to: 'msession#create'

  get '/sort_date', to: 'police#sortable'
  get '/sort_loc', to: 'police#sortablel'
  get '/sort_res', to: 'police#sortr'

  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/police.rb
class Police < ApplicationRecord
  has_secure_password
end

app/controllers/police_controller.rb
class PoliceController < ApplicationController
  before_action :set_police, only: [:show, :edit, :update, :destroy]

  # GET /police
  # GET /police.json
  def index
    if session[:police_id] != nil
      if session[:cas] == nil
        if session[:casl] == nil
          @police = Police.all
          @cases = Report.all
        else
          @police = Police.all
          @cases = Report.order(:x, :y)
        end
      else
        @police = Police.all
        @cases = Report.order(created_at: :desc)
      end
    else
      redirect_to root_url
    end
  end

  def sortr
    session[:cas] = nil
    session[:pol] = nil
    redirect_to police_index_url
  end

  def sortable
    session[:cas] = Report.order(:created_at)
    session[:pol] = nil
    redirect_to police_index_url
  end

  def sortablel
    session[:pol] = Report.order(:x, :y)
    session[:cas] = nil
    redirect_to police_index_url
  end

  # GET /police/1
  # GET /police/1.json
  def show
  end

  # GET /police/new
  def new
    if session[:admin_id] != nil
      @police = Police.new
    else
      flash[:notice] = 'You must login as an admin to create new Policeman account'
    end
  end

  # GET /police/1/edit
  def edit
  end

  # POST /police
  # POST /police.json
  def create
    if session[:admin_id] != nil
      @police = Police.new(police_params)

      respond_to do |format|
        if @police.save
          format.html { redirect_to @police, notice: 'Police was successfully created.' }
          format.json { render :show, status: :created, location: @police }
        else
          format.html { render :new }
          format.json { render json: @police.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:notice] = 'You must login as an admin to create new Policeman account'
    end
  end

  # PATCH/PUT /police/1
  # PATCH/PUT /police/1.json
  def update
    if session[:admin_id] != nil
      respond_to do |format|
        if @police.update(police_params)
          format.html { redirect_to @police, notice: 'Police was successfully updated.' }
          format.json { render :show, status: :ok, location: @police }
        else
          format.html { render :edit }
          format.json { render json: @police.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:notice] = 'You must login as an admin to create new Policeman account'
    end
  end

  # DELETE /police/1
  # DELETE /police/1.json
  def destroy
    if session[:admin_id] != nil
      @police.destroy
      respond_to do |format|
        format.html { redirect_to police_index_url, notice: 'Police was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:notice] = 'You must login as an admin to create new Policeman account'
    end
  end

  private
    def sort_column
      Report.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_police
      @police = Police.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def police_params
      params.require(:police).permit(:police_id, :username, :password, :name)
    end
end

app/helpers/police_helper.rb
module PoliceHelper
end

app/views/police/_form.html.erb
<%= form_for(police) do |f| %>
  <% if police.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(police.errors.count, "error") %> prohibited this police from being saved:</h2>

      <ul>
      <% police.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/police/edit.html.erb
<h1>Editing Police</h1>

<%= render 'form', police: @police %>

<%= link_to 'Show', @police %> |
<%= link_to 'Back', police_index_path %>

app/views/police/index.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Police Reports</h1>
<%= link_to 'Sort by date', sort_date_path %> |
<%= link_to 'Sort by location', sort_loc_path %>
<%= link_to 'Reset Sort', sort_res_path %>

<table border="4" bgcolor="F9FAED" align="center" width="100%" text-align="center">
  <thead>
    <tr>
      <th>Text</th>
      <th>Video</th>
      <th>Photo</th>
      <th>Person Name</th>
      <th>Location</th>
      <th>Done</th>
      <th>Date Time</th>
    </tr>
  </thead>

  <tbody style="text-align:center;">
    <% @cases.each do |cases| %>
      <tr>
        <td text-align="center"><%= cases.text %></td>
        <td text-align="center"><%= link_to 'Click Here', cases %></td>
        <td text-align="center"><img src="/reports/<%= cases.photo %>" width="100" height="100"/></td>
        <td text-align="center"><%= (Person.find(cases.personId)).name %></td>
        <td text-align="center"><%= link_to 'Click Here', cases.location %></td>
        <td text-align="center"><%= cases.done %></td>
        <td text-align="center"><%= cases.created_at %></td>
        <td text-align="center"><%= link_to 'Show', cases %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<br>

<%= link_to 'Logout', logout_path %>

app/views/police/new.html.erb
<h1>New Police</h1>

<%= render 'form', police: @police %>

<%= link_to 'Back', police_index_path %>

app/views/police/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Welcome Back, </strong>
  <%= @police.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @police.username %>
</p>

<p>
  <strong>Password: *****</strong>
  <%= @police.password %>
</p>



<%= link_to 'Click here to access database', if session[:police_id] == nil
                                              admins_path
                                            else
                                              police_index_url
                                            end %> |
<%= link_to 'Logout', logout_path %>