config/routes.rb
Rails.application.routes.draw do

  resources :admins
  get 'sessions/new'

  resources :reports
  resources :people
  resources :police

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  post '/mlogin', to: 'msession#create'

  get '/sort_date', to: 'police#sortable'
  get '/sort_loc', to: 'police#sortablel'
  get '/sort_res', to: 'police#sortr'

  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.order(:created_at)
  end

  def sortable
    @reports = Report.order(:created_at)
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report.done = true
    @report.update(report_params)
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to police_index_path, notice: 'Report was successfully created.' }
        format.json { render :index, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Report.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.permit(:text, :video, :photo, :sound, :personId, :done, :location)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(report) do |f| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.text_field :video %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  </div>

  <div class="field">
    <%= f.label :sound %>
    <%= f.text_field :sound %>
  </div>

  <div class="field">
    <%= f.label :personId %>
    <%= f.text_field :personId %>
  </div>

  <div class="field">
    <%= f.label :done %>
    <%= f.text_field :done %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>
<%= link_to 'Sort by date', sort_date_path %> |
<%= link_to 'Sort by location', sort_loc_path %>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Video</th>
      <th>Photo</th>
      <th>Sound</th>
      <th>Personid</th>
      <th>Done</th>
      <th>Location</th>
      <th>Date Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.text %></td>
        <td><%= report.video %></td>
        <td><%= report.photo %></td>
        <td><%= report.sound %></td>
        <td><%= report.personId %></td>
        <td><%= report.done %></td>
        <td><%= report.location %></td>
        <td><%= report.created_at %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @report.text %>
</p>

<p>
  <video id="my-video" preload="auto" width="340" height="264"
  poster="<%= @report.photo %>" data-setup="{}" autoplay="true" controls="play">
    <source src="<%= @report.video %>" type='video/mp4'>

  </video>

</p>

<p>
  <strong>Photo:</strong>
  <img src="<%= @report.photo %>" height="500"/>
</p>

<p>
  <strong>Sound:</strong>
  <embed src="<%= @report.sound %>" width="100" height="50"/>
</p>

<p>
  <strong>Personid:</strong>
  <%= (person = Person.find(@report.personId)).name %>
  <%= link_to 'show this person Information', person %>
</p>

<p>
  <strong>Done:</strong>
  <%= @report.done %>
</p>

<p>
  <strong>Location:</strong>
  <%= link_to 'Click Here', @report.location %>
</p>

<%= link_to 'Back', police_index_path %>